build: false
version: dev-{build}
clone_folder: C:\projects\cache-wincache

environment:
  matrix:
    - php_ver: 7.2.4

cache:
  - '%APPDATA%\Composer'
  - '%LOCALAPPDATA%\Composer'
  - C:\tools\php -> .appveyor.yml
  - C:\tools\composer.phar -> .appveyor.yml

init:
  - SET PATH=C:\tools\php;%PATH%

install:
  - ps: Set-Service wuauserv -StartupType Manual
  - IF NOT EXIST C:\tools\php (choco install --yes --allow-empty-checksums php --version %php_ver% --params '/InstallDir:C:\tools\php')
  - cd C:\tools\php
  - copy php.ini-production php.ini
  - echo date.timezone="UTC" >> php.ini
  - echo memory_limit=512M >> php.ini
  - echo extension_dir=ext >> php.ini
  - echo extension=php_mbstring.dll >> php.ini
  - echo extension=php_openssl.dll >> php.ini
  - echo extension=php_curl.dll >> php.ini
  - echo extension=php_fileinfo.dll >> php.ini
  - echo extension=php_wincache.dll >> php.ini
  - echo wincache.enablecli=1 >> php.ini
  - IF NOT EXIST C:\tools\composer.phar (cd C:\tools && appveyor DownloadFile https://getcomposer.org/download/1.4.1/composer.phar)
  - cd C:\tools\php\ext
  - choco install 7zip.install
  - appveyor DownloadFile https://netcologne.dl.sourceforge.net/project/wincache/development/wincache-2.0.0.8-dev-7.2.beta2-nts-vc15-x64.exe
  - 7z e wincache-2.0.0.8-dev-7.2.beta2-nts-vc15-x64.exe

before_test:
  - cd C:\projects\cache-wincache
  - php C:\tools\composer.phar update --no-interaction --no-progress --prefer-stable --no-ansi

test_script:
  - cd C:\projects\cache-wincache
  - vendor\bin\phpunit
